### ISSUE TITLE
Can't setup method invocation when parameter isn't under test method's control

### ISSUE THREAD

**Issue by nelsonghezzi** [steve-hyperbolic/hyper#1]
Hi, I've been trying HyperMock.Universal to test some UWP project.

It works great for some simple cases, but I've hit a wall in the situation described below.

Say I'm testing ServiceA. ServiceA collaborates with some ServiceB. To perform its job, ServiceA takes an int value and constructs some Result object, which in turn handles to ServiceB.Bar method.

I'm not testing ServiceB.Bar method, so I don't care what ServiceB.Bar method does with the result object.

The problem arises mocking ServiceB and trying to Setup its Bar method, because I'm not in control of the identity of the Result instance when it gets called.

Some sample code to get an idea:

In Service A:
```
public Result Foo(int value)
{
    Result result = new Result(value * 2);

    this.serviceB.Bar(result);

    return result;
}
```

In Test class:
```
[TestMethod]
public void TestMethod()
{
    // arrange
    IServiceB serviceB = Mock.Create<IServiceB>();

    ServiceA serviceA = new ServiceA(serviceB);

    // I'm passing a 'null' placeholder to the Bar invokation
    serviceB.Setup(x => x.Bar(null));

    // act
    // the invokation of ServiceA.Foo method fails when it gets to call the mocked ServiceB.Bar method
    Result result = serviceA.Foo(5); 

    // assert
    Assert.AreEqual(result.Value, 10);

    serviceB.Verify(x => x.Bar(null), Occurred.Once());
}
```
As a side note, changing the source of ServiceA.Foo to pass null in ServiceB.Bar invokation makes the test pass.

Is this a known limitation of the DispatchProxy class or its use in HyperMock.Universal?

Thanks!

p.s.: all the code is roughly an example, if you need the full code let me know.

**Comment by steve-hyperbolic** [comment]
Hi Nelson

Thanks for the query.

This appears to be a case where you need to use the Param.IsAny<>.

If I have understood your example correctly, see:

[TestClass]
    public class MyTest
    {
        [TestMethod]
        public void TestServiceFoo()
        {
            // arrange
            IServiceB serviceB = Mock.Create<IServiceB>();

            ServiceA serviceA = new ServiceA(serviceB);

            // I'm passing a 'null' placeholder to the Bar invokation
            serviceB.Setup(x => x.Bar(**Param.IsAny<object>()));**

            // act
            // the invokation of ServiceA.Foo method fails when it gets to call the mocked ServiceB.Bar method
            Result result = serviceA.Foo(5);

            // assert
            Assert.AreEqual(result.Value, 10);

            serviceB.Verify(x => x.Bar(null), Occurred.Once());

        }
    }

    public interface IServiceB
    {
        void Bar(object obj);
    }

    public class ServiceA
    {
        private readonly IServiceB _serviceB;

        public ServiceA(IServiceB serviceB)
        {
            _serviceB = serviceB;
        }

        public Result Foo(int x)
        {
            _serviceB.Bar(new object());

            return new Result {Value = 10};
        }
    }

    public class Result
    {
        public int Value { get; set; }
    }

The bit in bold is where you need to make the change as you state that you do not control what is passed to the mock.

Hope this help

Kind regards
Steve

**Comment by steve-hyperbolic** [comment]
Hi Nelson

No problem. I will review the example docs later and add it to the example list too. I didn't add every scenario into those docs but might be worth adding this one.

Also to help others, it could be added to StackOverflow too. 

Kind regards
Steve
